import type { ComponentTokenMap } from './types'

export const DEFAULT_COMPONENT_TOKENS: ComponentTokenMap = {
  'button-primary': {
    'bg':          'var(--color-interactive)',
    'text':        'var(--color-on-interactive)',
    'bg-hover':    'var(--color-interactive-hover)',
    'border':      'transparent',
    'radius':      'var(--radius-md)',
    'padding-x':   'var(--space-5)',
    'padding-y':   'var(--space-2)',
    'font-size':   'var(--text-sm)',
    'font-weight': '600',
  },
  'button-secondary': {
    'bg':       'transparent',
    'text':     'var(--color-interactive)',
    'bg-hover': 'var(--color-interactive-subtle)',
    'border':   'var(--color-interactive)',
    'radius':   'var(--radius-md)',
  },
  'button-ghost': {
    'text':       'var(--color-on-surface)',
    'text-hover': 'var(--color-interactive)',
    'bg-hover':   'var(--color-interactive-subtle)',
    'border':     'transparent',
  },
  'button-danger': {
    'bg':       'var(--color-error)',
    'text':     'var(--color-on-error)',
    'bg-hover': 'var(--color-error-container)',
  },
  'input': {
    'bg':           'var(--color-surface)',
    'border':       'var(--color-border)',
    'border-focus': 'var(--color-interactive)',
    'border-error': 'var(--color-error)',
    'text':         'var(--color-on-surface)',
    'placeholder':  'var(--color-on-surface-subtle)',
    'radius':       'var(--radius-base)',
    'padding-x':    'var(--space-4)',
    'padding-y':    'var(--space-2)',
  },
  'select': {
    'bg':            'var(--color-surface)',
    'border':        'var(--color-border)',
    'border-focus':  'var(--color-interactive)',
    'border-error':  'var(--color-error)',
    'text':          'var(--color-on-surface)',
    'placeholder':   'var(--color-on-surface-subtle)',
    'radius':        'var(--radius-base)',
    'padding-x':     'var(--space-4)',
    'padding-y':     'var(--space-2)',
    'chevron-color': 'var(--color-on-surface-subtle)',
  },
  'textarea': {
    'bg':           'var(--color-surface)',
    'border':       'var(--color-border)',
    'border-focus': 'var(--color-interactive)',
    'border-error': 'var(--color-error)',
    'text':         'var(--color-on-surface)',
    'placeholder':  'var(--color-on-surface-subtle)',
    'radius':       'var(--radius-base)',
    'padding-x':    'var(--space-4)',
    'padding-y':    'var(--space-3)',
    'resize':       'vertical',
  },
  'checkbox': {
    'bg-checked':      'var(--color-interactive)',
    'border':          'var(--color-border-strong)',
    'border-checked':  'var(--color-interactive)',
    'checkmark-color': 'var(--color-on-interactive)',
    'radius':          'var(--radius-sm)',
  },
  'card': {
    'bg':      'var(--color-surface)',
    'border':  'var(--color-border)',
    'radius':  'var(--radius-lg)',
    'shadow':  'var(--shadow-sm)',
    'padding': 'var(--space-6)',
  },
  'badge-success': { 'bg': 'var(--color-success-container)', 'text': 'var(--color-on-success-container)', 'border': 'transparent' },
  'badge-warning': { 'bg': 'var(--color-warning-container)', 'text': 'var(--color-on-warning-container)', 'border': 'transparent' },
  'badge-error':   { 'bg': 'var(--color-error-container)',   'text': 'var(--color-on-error-container)',   'border': 'transparent' },
  'badge-info':    { 'bg': 'var(--color-info-container)',    'text': 'var(--color-on-info-container)',    'border': 'transparent' },
  'badge-neutral': { 'bg': 'var(--color-surface-overlay)',  'text': 'var(--color-on-surface)',           'border': 'var(--color-border)' },
  'tag': {
    'bg':     'var(--color-surface-raised)',
    'text':   'var(--color-on-surface)',
    'border': 'var(--color-border)',
    'radius': 'var(--radius-full)',
  },
  'tooltip': {
    'bg':     'var(--color-inverse-surface)',
    'text':   'var(--color-on-inverse-surface)',
    'radius': 'var(--radius-sm)',
  },
  'nav-item': {
    'text':          'var(--color-on-surface-subtle)',
    'text-active':   'var(--color-interactive)',
    'bg-active':     'var(--color-interactive-subtle)',
    'border-active': 'var(--color-interactive)',
  },
  'table': {
    'bg':           'var(--color-surface)',
    'border':       'var(--color-border)',
    'header-bg':    'var(--color-surface-raised)',
    'row-hover-bg': 'var(--color-interactive-subtle)',
    'text':         'var(--color-on-surface)',
  },
}
