import type { ArchetypeDefinition, ArchetypeId } from './types'

export const ARCHETYPES: Record<ArchetypeId, ArchetypeDefinition> = {
  bold: {
    id: 'bold',
    name: 'Bold',
    description: 'High-impact, confident, brand-forward.',
    colorParams: { lRange: [0.48, 0.60], cRange: [0.18, 0.26] },
    harmonyModel: 'complementary',
    typography: {
      headingFonts: ['Syne', 'Space Grotesk', 'DM Sans'],
      bodyFonts: ['Inter', 'DM Sans'],
      headingWeightRange: [800, 900],
      bodyWeightRange: [400, 500],
      defaultPairings: [
        { heading: 'Syne', body: 'Inter' },
        { heading: 'Space Grotesk', body: 'DM Sans' },
        { heading: 'DM Sans', body: 'Inter' },
      ],
    },
    spacing: { base: 8, density: 'balanced' },
    radiusBase: 6,
    defaultShowcase: 'marketing',
  },
  editorial: {
    id: 'editorial',
    name: 'Editorial',
    description: 'Sophisticated, typography-led, content-first.',
    colorParams: { lRange: [0.38, 0.65], cRange: [0.06, 0.14], preferredHue: 50 },
    harmonyModel: 'analogous',
    typography: {
      headingFonts: ['Fraunces', 'Playfair Display', 'DM Serif Display'],
      bodyFonts: ['Source Serif 4', 'Lora', 'EB Garamond'],
      headingWeightRange: [400, 700],
      bodyWeightRange: [400, 400],
      defaultPairings: [
        { heading: 'Fraunces', body: 'Source Serif 4' },
        { heading: 'Playfair Display', body: 'Lora' },
        { heading: 'DM Serif Display', body: 'EB Garamond' },
      ],
    },
    spacing: { base: 8, density: 'airy' },
    radiusBase: 2,
    defaultShowcase: 'editorial',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Restrained, functional, high signal-to-noise.',
    colorParams: { lRange: [0.40, 0.70], cRange: [0.04, 0.10], preferredHue: 240 },
    harmonyModel: 'monochromatic',
    typography: {
      headingFonts: ['DM Sans', 'Inter'],
      bodyFonts: ['DM Sans', 'Inter'],
      headingWeightRange: [600, 700],
      bodyWeightRange: [400, 400],
      defaultPairings: [
        { heading: 'DM Sans', body: 'DM Sans' },
        { heading: 'Inter', body: 'Inter' },
        { heading: 'DM Sans', body: 'Inter' },
      ],
    },
    spacing: { base: 8, density: 'airy' },
    radiusBase: 4,
    defaultShowcase: 'dashboard',
  },
  playful: {
    id: 'playful',
    name: 'Playful',
    description: 'Energetic, expressive, approachable.',
    colorParams: { lRange: [0.52, 0.70], cRange: [0.20, 0.30], preferredHue: 30 },
    harmonyModel: 'triadic',
    typography: {
      headingFonts: ['Nunito', 'Poppins'],
      bodyFonts: ['Nunito', 'Quicksand'],
      headingWeightRange: [700, 800],
      bodyWeightRange: [500, 500],
      defaultPairings: [
        { heading: 'Nunito', body: 'Nunito' },
        { heading: 'Poppins', body: 'Nunito' },
        { heading: 'Poppins', body: 'Quicksand' },
      ],
    },
    spacing: { base: 8, density: 'balanced' },
    radiusBase: 12,
    defaultShowcase: 'marketing',
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    description: 'Structured, trustworthy, clear.',
    colorParams: { lRange: [0.38, 0.58], cRange: [0.10, 0.17], preferredHue: 235 },
    harmonyModel: 'split-complementary',
    typography: {
      headingFonts: ['Outfit', 'Nunito Sans', 'IBM Plex Sans'],
      bodyFonts: ['Outfit', 'Nunito Sans', 'IBM Plex Sans'],
      headingWeightRange: [600, 700],
      bodyWeightRange: [400, 400],
      defaultPairings: [
        { heading: 'Outfit', body: 'Outfit' },
        { heading: 'IBM Plex Sans', body: 'IBM Plex Sans' },
        { heading: 'Nunito Sans', body: 'Nunito Sans' },
      ],
    },
    spacing: { base: 8, density: 'balanced' },
    radiusBase: 4,
    defaultShowcase: 'dashboard',
  },
  technical: {
    id: 'technical',
    name: 'Technical',
    description: 'Precise, systematic, data-forward.',
    colorParams: { lRange: [0.42, 0.60], cRange: [0.08, 0.15], preferredHue: 200 },
    harmonyModel: 'complementary',
    typography: {
      headingFonts: ['IBM Plex Sans', 'DM Sans'],
      bodyFonts: ['IBM Plex Sans', 'DM Mono'],
      headingWeightRange: [600, 600],
      bodyWeightRange: [400, 400],
      defaultPairings: [
        { heading: 'IBM Plex Sans', body: 'IBM Plex Sans' },
        { heading: 'DM Sans', body: 'IBM Plex Sans' },
        { heading: 'IBM Plex Sans', body: 'DM Mono' },
      ],
    },
    spacing: { base: 4, density: 'compact' },
    radiusBase: 2,
    defaultShowcase: 'dashboard',
  },
}
